baseURL: 'https://plaguss.github.io/'
languageCode: en-us
title: Agus site
theme: PaperMod
Paginate: 15
preserveTaxonomyNames: true
enableRobotsTXT: true
pygmentsCodefences: true
enableEmoji: true
defaultContentLanguage: en

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
pygmentsUseClasses: true

languages:
  en:
    languageName: "English"
    weight: 1
    taxonomies:
      category: categories
      tag: tags
      series: series
    menu:
      main:
        - identifier: categories
          name: Categories
          url: /categories/
          weight: 10
        - identifier: tags
          name: Tags
          url: /tags/
          weight: 20

    params:
      defaultTheme: auto # to switch between dark or light according to browser theme
      ShowCodeCopyButtons: true
      ShowToc: true
      homeInfoParams:
        # enabled: true
        Title: Hi there
        Content: >-
          Hi, this is Agus. I love open source and building things with python.
          Maybe writing about them here helps other people, at least it will
          be stored for my future self. Other than that I may be doing
          CrossFit or watching The Office.
        # imageUrl: >-
        #   https://raw.githubusercontent.com/plaguss/plaguss.github.io/main/.github/images/pic.jpg
        # imageTitle: Agus
        # imageWidth: 320
        # imageHeight: 320
        # buttons:
        #   - name: Blog
        #     url: /blog
      socialIcons:
        - name: Github
          url: 'https://github.com/plaguss/'
        - name: LinkedIn
          url: 'https://www.linkedin.com/in/agustín-piqueres-lajarín-6a661810a'

      info:
        description: ''
        title404: Nothing's here!
      settings:
        dateFormat: '2006-01-02'
        listDateFormat: '2006-01-02'
        archiveDateFormat: Jan 02
        hideEntryNavigation:
          - page
        hideSocialMenu: true
        showReadingTime: true
        taxonomyCloudShuffle: true
        accentColor: '#297FD5'
      sidebar:
        enable: true
      widgets:
        homepage:
          - recent_posts
        sidebar:
          - about
      social:
        email: agustin.piqueres@gmail.com
        github: plaguss
      ShowReadingTime: true
      ShowPostNavLinks: true

  es:
    languageName: "Español"
    languageAltTitle: Español
    weight: 2
    menu:
      main:
        - identifier: categories
          name: Categories
          url: /categories/
          weight: 10
        - identifier: tags
          name: Tags
          url: /tags/
          weight: 20

    params:
      defaultTheme: auto # to switch between dark or light according to browser theme
      ShowCodeCopyButtons: true
      ShowToc: true
      homeInfoParams:
        # enabled: true
        Title: Hola
        Content: >-
          Hola, me llamo Agus. Me encanta el código libre y construir cosas con
          Python. Quizá escribiendo de ellas aquí ayude a otras personas, al
          menos estará guardado para mi yo futuro.
          A parte de esto es posible que esté haciendo CrossFit o viendo
          The Office.
        # imageUrl: >-
        #   https://raw.githubusercontent.com/plaguss/plaguss.github.io/main/.github/images/pic.jpg
        # imageTitle: Agus
        # imageWidth: 320
        # imageHeight: 320
        # buttons:
        #   - name: Blog
        #     url: /blog
      socialIcons:
        - name: Github
          url: 'https://github.com/plaguss/'
        - name: LinkedIn
          url: 'https://www.linkedin.com/in/agustín-piqueres-lajarín-6a661810a'

      info:
        description: ''
        title404: Nothing's here!
      settings:
        dateFormat: '2006-01-02'
        listDateFormat: '2006-01-02'
        archiveDateFormat: Jan 02
        hideEntryNavigation:
          - page
        hideSocialMenu: true
        showReadingTime: true
        taxonomyCloudShuffle: true
        accentColor: '#297FD5'
      sidebar:
        enable: true
      widgets:
        homepage:
          - recent_posts
        sidebar:
          - about
      social:
        email: agustin.piqueres@gmail.com
        github: plaguss
      ShowReadingTime: true
      ShowPostNavLinks: true


outputs:
  home:
    - HTML
    - RSS
    - JSON
